name: pull & push

on:
  push:
    branches:
      - master

jobs:
  main:
    name: pull and push
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - name: pull and push
      run: bash work.sh
